default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: fdep_admin
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: fdep_development

test:
  <<: *default
  database: fdep_test

production:
  <<: *default
  database: fdep_production
  username: fdep_admin
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>